# Generated by Django 2.1.3 on 2019-01-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_createprofie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createprofie',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
