# Generated by Django 2.1.3 on 2019-01-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190104_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createprofie',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
