"""
Django settings for atreat project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8@2ebflid95bg8t27enp2+j(9hp#c$y*jbq=*&a9if9ylkra@3'

# SECURITY WARNING: don't run with debug turned on in production!
<<<<<<< HEAD
DEBUG = False

ALLOWED_HOSTS = ['www.atreat4u.com.ng']
=======
DEBUG = True

ALLOWED_HOSTS = []
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'catalog',
    'cart',
    'order',
<<<<<<< HEAD
    'crispy_forms',
    'twilio',

]


=======
    'payu_biz',
    'crispy_forms',

]

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'atreat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'atreat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
<<<<<<< HEAD
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'richardowota$default',
        'USER': 'richardowota',
        'PASSWORD': 'bossess1',
        'HOST': 'richardowota.mysql.pythonanywhere-services.com',
=======
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = (
 'django.contrib.auth.backends.ModelBackend',
 'account.AuthBackend.EmailAuthBackend',
<<<<<<< HEAD
)
=======
) 
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

<<<<<<< HEAD
TIME_ZONE = 'Africa/Bangui'
=======
TIME_ZONE = 'UTC'
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c

USE_I18N = True

USE_L10N = True

USE_TZ = True

<<<<<<< HEAD
LOGOUT_REDIRECT_URL = 'account/login/'
=======

>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
<<<<<<< HEAD
#STATICFILES_DIRS = '/home/richardowota/website/atreat/static'
STATIC_ROOT = '/home/richardowota/website/atreat/static'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/home/richardowota/website/atreat/media_cdn'
CRISPY_TEMPLATE_PACK='bootstrap3'

SION_COOKIE_AGE = 7776000
CART_SESSION_ID = 'cart'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_TLS=True

EMAIL_HOST='smtp.gmail.com'

EMAIL_HOST_USER='gospeltruth18@gmail.com'

EMAIL_HOST_PASSWORD='bossess1'

EMAIL_PORT=587

DEFAULT_FROM_EMAIL = 'gospeltruth18@gmail.com'

SERVER_EMAIL = 'gospeltruth18@gmail.com'

CRISPY_TEMPLATE_PACK='bootstrap4'
=======
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static_cdn')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_cdn')
CRISPY_TEMPLATE_PACK='bootstrap3'

SION_COOKIE_AGE = 7776000
CART_SESSION_ID = 'cart'
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c
