# Generated by Django 2.0 on 2018-09-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealprice',
            old_name='restaurant',
            new_name='real_restaurant',
        ),
    ]
