# Generated by Django 2.1.3 on 2019-02-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_usercinemas_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebritybid',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rebidceleb',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercinemas',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercomedydouble',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercomedyround',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercomedysingle',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercomedyvip',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermeal',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersalon',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
