# Generated by Django 2.0 on 2018-09-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_usercinemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercinemas',
            name='time',
            field=models.CharField(default='3pm', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercinemas',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
