# Generated by Django 2.0 on 2018-09-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20180916_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSalon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('style', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('gender', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
            ],
        ),
    ]
