# Generated by Django 2.0 on 2018-09-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_usercomedy'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComedyDouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=200)),
                ('double_price', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserComedyRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=200)),
                ('round_table_price', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserComedySingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=200)),
                ('singles_price', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserComedyVip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=200)),
                ('vip_table_price', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='UserComedy',
        ),
    ]
