# Generated by Django 2.0 on 2018-09-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20180917_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomedydouble',
            name='category',
            field=models.CharField(default='double', max_length=30),
        ),
        migrations.AddField(
            model_name='usercomedyround',
            name='category',
            field=models.CharField(default='Round Table', max_length=30),
        ),
        migrations.AddField(
            model_name='usercomedysingle',
            name='category',
            field=models.CharField(default='single', max_length=30),
        ),
        migrations.AddField(
            model_name='usercomedyvip',
            name='category',
            field=models.CharField(default='Vip Table', max_length=30),
        ),
    ]
