# Generated by Django 2.0 on 2018-09-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20180917_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomedysingle',
            name='category',
            field=models.CharField(default='singles', max_length=30),
        ),
    ]
