# Generated by Django 2.0 on 2018-09-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20180917_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomedydouble',
            name='category',
            field=models.CharField(default='Double', max_length=30),
        ),
        migrations.AlterField(
            model_name='usercomedysingle',
            name='category',
            field=models.CharField(default='Singles', max_length=30),
        ),
    ]
