# Generated by Django 2.0 on 2018-10-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20180920_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeal',
            name='user',
            field=models.CharField(default='omonbude', max_length=50),
            preserve_default=False,
        ),
    ]
