# Generated by Django 2.0 on 2018-10-26 11:17

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_celebritybid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebritybid',
            name='user',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=50),
        ),
    ]
