# Generated by Django 2.0 on 2018-10-31 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20181026_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CelebrityBid',
            new_name='MovieBid',
        ),
    ]
