# Generated by Django 2.0 on 2018-11-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_rebidceleb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rebidceleb',
            name='user',
        ),
    ]
