# Generated by Django 2.0 on 2018-11-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_auto_20181103_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebidceleb',
            name='celeb',
            field=models.CharField(default='omotola', max_length=50),
            preserve_default=False,
        ),
    ]
