# Generated by Django 2.0 on 2018-11-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_rebidceleb_celeb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebidceleb',
            name='celeb',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
