# Generated by Django 2.0 on 2018-11-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_mealquantityform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MealQuantityForm',
            new_name='MealQuantity',
        ),
    ]
