# Generated by Django 2.0 on 2018-11-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_auto_20181112_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeal',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
