# Generated by Django 2.0 on 2018-11-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_usermeal_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
