# Generated by Django 2.0 on 2018-11-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_auto_20181113_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercinemas',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
