<<<<<<< HEAD
# Generated by Django 2.0 on 2018-10-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecipientName', models.CharField(max_length=50)),
                ('RecipientPhoneNumber', models.CharField(max_length=50)),
                ('TreatOccasion', models.CharField(max_length=50)),
                ('SpecialNote', models.TextField()),
            ],
        ),
    ]
=======
# Generated by Django 2.0 on 2018-10-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecipientName', models.CharField(max_length=50)),
                ('RecipientPhoneNumber', models.CharField(max_length=50)),
                ('TreatOccasion', models.CharField(max_length=50)),
                ('SpecialNote', models.TextField()),
            ],
        ),
    ]
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c
