<<<<<<< HEAD
# Generated by Django 2.0 on 2018-11-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='SpecialNote',
            field=models.TextField(help_text='not more than 30 words', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='TreatOccasion',
            field=models.CharField(help_text='e.g birthday, marriage, matric etc..', max_length=50),
        ),
    ]
=======
# Generated by Django 2.0 on 2018-11-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='SpecialNote',
            field=models.TextField(help_text='not more than 30 words', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='TreatOccasion',
            field=models.CharField(help_text='e.g birthday, marriage, matric etc..', max_length=50),
        ),
    ]
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c
