<<<<<<< HEAD
# Generated by Django 2.0 on 2018-11-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20181113_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='SpecialNote',
            field=models.TextField(help_text='not more than 30 words', max_length=30),
        ),
    ]
=======
# Generated by Django 2.0 on 2018-11-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20181113_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='SpecialNote',
            field=models.TextField(help_text='not more than 30 words', max_length=30),
        ),
    ]
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c
