<<<<<<< HEAD
# Generated by Django 2.1.3 on 2019-01-04 23:58
=======
# Generated by Django 2.0 on 2018-08-20 00:31
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='BusinessBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='none', max_length=100)),
                ('celeb', models.CharField(default='none', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cbid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='none', max_length=100)),
                ('celeb', models.CharField(default='none', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CelebrityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Nollywood Celebrities', 'Nollywood Celebrities'), ('musical Artist Celebrities', 'musical Artist Celebrities'), ('Business Icon Celebrities', 'Business Icon Celebrities'), ('TV Host Celebrities', 'TV Host Celebrities')], max_length=100)),
                ('category_slug', models.SlugField()),
                ('movie', models.FileField(upload_to='')),
                ('slug', models.SlugField()),
                ('charity_name', models.CharField(max_length=100)),
                ('charity_image', models.ImageField(upload_to='')),
                ('treat_description', models.CharField(max_length=500)),
                ('start_bid', models.DecimalField(decimal_places=2, default=5000.0, max_digits=15, max_length=50)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CinemaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema', models.CharField(blank=True, max_length=2000, null=True)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CinemaLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CinemasDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('rating', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('cinema_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_name', to='catalog.Cinemas')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_location', to='catalog.CinemaLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Comedy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=200)),
                ('singles_price', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
                ('double_price', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
                ('round_table_price', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
                ('vip_table_price', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('Menu', models.CharField(max_length=50)),
                ('Brand', models.CharField(blank=True, max_length=50, null=True)),
                ('Size', models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50, null=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
                ('available', models.BooleanField(default=True)),
=======
                ('real_restaurant', models.CharField(max_length=50)),
                ('Menu', models.CharField(max_length=50)),
                ('Brand', models.CharField(blank=True, max_length=50, null=True)),
                ('Size', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location1', to='catalog.Location')),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='MusicBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='none', max_length=100)),
                ('celeb', models.CharField(default='none', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(blank=True, max_length=2000, null=True)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
<<<<<<< HEAD
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('venue', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SalonDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('style', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_name', to='catalog.Salon')),
            ],
        ),
        migrations.CreateModel(
            name='TvhostBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='none', max_length=100)),
                ('celeb', models.CharField(default='none', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
=======
                ('image', models.ImageField(upload_to='')),
            ],
        ),
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c
        migrations.AddField(
            model_name='meal',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='catalog.Restaurants'),
        ),
        migrations.AddField(
            model_name='location',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_location', to='catalog.Restaurants'),
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='cinemalocation',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_location', to='catalog.Cinemas'),
        ),
=======
>>>>>>> 714da70c489406f200282bb4a66b5e38148dfd8c
    ]
