# Generated by Django 2.1.3 on 2019-02-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbid',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbid',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musicbid',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvhostbid',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
