# Generated by Django 2.1.3 on 2019-03-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_logoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbid',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, max_length=50),
        ),
    ]
