# Generated by Django 2.1.3 on 2019-03-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_cbid_amount_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicbid',
            name='new_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, max_length=50),
        ),
        migrations.AddField(
            model_name='musicbid',
            name='new_amount_paid',
            field=models.BooleanField(default=False),
        ),
    ]
