# Generated by Django 2.1.3 on 2019-03-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190312_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessbid',
            name='new_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, max_length=50),
        ),
        migrations.AddField(
            model_name='businessbid',
            name='new_amount_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cbid',
            name='new_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, max_length=50),
        ),
        migrations.AddField(
            model_name='cbid',
            name='new_amount_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tvhostbid',
            name='new_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, max_length=50),
        ),
        migrations.AddField(
            model_name='tvhostbid',
            name='new_amount_paid',
            field=models.BooleanField(default=False),
        ),
    ]
