# Generated by Django 2.0 on 2018-08-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_salondetail_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='salondetail',
            name='style',
            field=models.CharField(default='round cut', max_length=200),
            preserve_default=False,
        ),
    ]
