# Generated by Django 2.0 on 2018-08-28 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_cinemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemasDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('rating', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_name', to='catalog.Cinemas')),
            ],
        ),
    ]
