# Generated by Django 2.0 on 2018-08-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_cinemasdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='slug',
            field=models.SlugField(default='slug-field'),
            preserve_default=False,
        ),
    ]
