# Generated by Django 2.0 on 2018-08-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180829_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemasdetail',
            name='cinema_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_name', to='catalog.Cinemas'),
        ),
    ]
