# Generated by Django 2.0 on 2018-08-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_celebrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='category',
            field=models.CharField(choices=[('Nollywood Celebrities', 'Nollywood Celebrities'), ('musical Artist Celebrities', 'musical Artist Celebrities'), ('Business Icon Celebrities', 'Business Icon Celebrities'), ('TV Host Celebrities', 'TV Host Celebrities')], default='Business Icon Celebrities', max_length=100),
            preserve_default=False,
        ),
    ]
