# Generated by Django 2.0 on 2018-08-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_celebrity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='image',
            field=models.ImageField(default='bude.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
