# Generated by Django 2.0 on 2018-08-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_celebrity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='category_slug',
            field=models.SlugField(default='slug-field'),
            preserve_default=False,
        ),
    ]
