# Generated by Django 2.0 on 2018-09-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_celebrity_category_slug'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='meal',
            index_together={('id', 'real_restaurant')},
        ),
    ]
