# Generated by Django 2.0 on 2018-09-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20180909_2121'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='meal',
            index_together=set(),
        ),
    ]
