# Generated by Django 2.0 on 2018-09-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20180909_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='Size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50, null=True),
        ),
    ]
