# Generated by Django 2.0 on 2018-09-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20180920_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='location_slug',
            field=models.SlugField(default='isiohor'),
            preserve_default=False,
        ),
    ]
