# Generated by Django 2.0 on 2018-09-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_meal_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_location', to='catalog.Restaurants'),
        ),
    ]
