# Generated by Django 2.0 on 2018-09-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20180922_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Restaurant',
            field=models.SlugField(),
        ),
    ]
