# Generated by Django 2.0 on 2018-09-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20180922_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_location', to='catalog.Restaurants'),
        ),
    ]
