# Generated by Django 2.0 on 2018-11-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_cinemalocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='treat_description',
            field=models.CharField(default='This Nollywood Icon and sensation is giving away atreat4u to host five of her fans to have a special dinner at her home on this Feb 13th eve of Valentine, Bidding for this treat is ongoing!', max_length=500),
            preserve_default=False,
        ),
    ]
