# Generated by Django 2.0 on 2018-11-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_celebrity_treat_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('Nollywood Celebrities', 'Nollywood Celebrities'), ('musical Artist Celebrities', 'musical Artist Celebrities'), ('Business Icon Celebrities', 'Business Icon Celebrities'), ('TV Host Celebrities', 'TV Host Celebrities')], max_length=100)),
                ('category_slug', models.SlugField()),
                ('movie', models.FileField(upload_to='')),
                ('slug', models.SlugField()),
                ('charity_name', models.CharField(max_length=100)),
                ('charity_image', models.ImageField(upload_to='')),
                ('treat_description', models.CharField(max_length=500)),
            ],
        ),
    ]
