# Generated by Django 2.0 on 2018-11-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_cbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbid',
            name='user',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
