# Generated by Django 2.0 on 2018-11-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20181105_0932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Celebrity',
        ),
    ]
