# Generated by Django 2.0 on 2018-11-13 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_businessbid_tvhostbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebritytest',
            name='end',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celebritytest',
            name='start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
